// <auto-generated />
using System;
using API.Usuarios.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Usuarios.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20211009184023_UpdateEmplid")]
    partial class UpdateEmplid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("API.Usuarios.Models.Alumno", b =>
                {
                    b.Property<int>("IdAlumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ApellidoPaterno")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Emplid")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdAlumno")
                        .HasName("IdAlumno");

                    b.ToTable("Alumno");
                });

            modelBuilder.Entity("API.Usuarios.Models.Configuracion", b =>
                {
                    b.Property<int>("IdConfiguracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Habilitar")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Periodo")
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdConfiguracion")
                        .HasName("PK_IdConfiguracion");

                    b.ToTable("Configuracion");
                });

            modelBuilder.Entity("API.Usuarios.Models.Log", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("IdMigracion")
                        .HasColumnType("int");

                    b.Property<string>("Request")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Response")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Tipo")
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdLog")
                        .HasName("PK_IdLog");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("API.Usuarios.Models.Migracion", b =>
                {
                    b.Property<int>("IdMigracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Emplid")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("NroIntento")
                        .HasColumnType("int");

                    b.Property<int>("NroMigracion")
                        .HasColumnType("int");

                    b.Property<string>("Periodo")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoMigracion")
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdMigracion")
                        .HasName("PK_IdMigracion");

                    b.ToTable("Migracion");
                });

            modelBuilder.Entity("API.Usuarios.Models.Periodo", b =>
                {
                    b.Property<int>("IdPeriodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NPeriodo")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdPeriodo")
                        .HasName("PK_IdPeriodo");

                    b.ToTable("Periodo");
                });

            modelBuilder.Entity("API.Usuarios.Models.Schedule", b =>
                {
                    b.Property<int>("IdSchedule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.HasKey("IdSchedule")
                        .HasName("PK_IdSchedule");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("API.Usuarios.Models.UsuarioCursoMoodle", b =>
                {
                    b.Property<int>("IdUsuarioCursoMoodle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Emplid")
                        .HasColumnType("int");

                    b.Property<string>("Strm")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("Sysdate")
                        .HasColumnType("datetime");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdUsuarioCursoMoodle")
                        .HasName("PK_IdUsuarioCursoMoodle");

                    b.ToTable("UsuarioCursoMoodle");
                });

            modelBuilder.Entity("API.Usuarios.Models.UsuarioCursoOracle", b =>
                {
                    b.Property<int>("IdUsuarioCursoOracle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcadCareer")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ClassNbr")
                        .HasColumnType("int");

                    b.Property<string>("ClassSection")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Emplid")
                        .HasColumnType("int");

                    b.Property<string>("OpridSemilla")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Roleid")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Strm")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Suspend")
                        .HasColumnType("int");

                    b.Property<DateTime>("Sysdate")
                        .HasColumnType("datetime");

                    b.Property<string>("Unidneg")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdUsuarioCursoOracle")
                        .HasName("PK_IdUsuarioCursoOracle");

                    b.ToTable("UsuarioCursoOracle");
                });
#pragma warning restore 612, 618
        }
    }
}
